services:
  app:
    image: ouuan/yaf2m
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./config:/app/config
  db:
    image: postgres:18-alpine
    env_file: .env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
